FROM centos:7

ARG APISIX_VERSION=1.2
LABEL apisix_version="${APISIX_VERSION}"

COPY rpm/apisix-$APISIX_VERSION-0.el7.noarch.rpm .

RUN yum -y install yum-utils\
    && yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo \
	&& yum install -y openresty wget tar \
	&& rpm -ivh apisix-$APISIX_VERSION-0.el7.noarch.rpm \
	&& yum clean all \
	&& rm -f apisix-$APISIX_VERSION-0.el7.noarch.rpm \
	&& sed -i 's/PASS_MAX_DAYS\t99999/PASS_MAX_DAYS\t60/g' /etc/login.defs

WORKDIR /usr/local/apisix


# add dashboard dist, 国内下载github release慢
# COPY dashboard/dist.tar.gz .
# RUN tar zxf dist.tar.gz \
#     && rm -f dist.tar.gz \
#     && mv dist dashboard

EXPOSE 9080 9443

CMD ["sh", "-c", "/usr/bin/apisix init && /usr/bin/apisix init_etcd && /usr/local/openresty/bin/openresty -p /usr/local/apisix -g 'daemon off;'"]